(function($){var page,isLandingPage,navLinks,navLinks_hasSubmenu,menuOpenEvent,isMobile,isModernWebkitMobile,topMargin,isFixedHeader,responsiveNavEnabled,hash_update_timer,sliders;$(document).ready(function(){$('html').removeClass('no-js');if($.sparkHelpers.isMobilePlatform()){isMobile=true;$("html").addClass("mobile");if($.sparkHelpers.isModernWebkit()){$("html").addClass("modern-mobile");isModernWebkitMobile=true;isFixedHeader=(sparkOptions.fixedHeader=="static"||sparkOptions.fixedHeader=="desktop-only")?false:true;}else{isModernWebkitMobile=false;isFixedHeader=false;}}else{isMobile=false;isModernWebkitMobile=false;isFixedHeader=(sparkOptions.fixedHeader=="static")?false:true;}
if(isFixedHeader){$("html").addClass("fixed-header");}else{$("html").addClass("static-header");}
if(isMobile||!isFixedHeader){page=$('html,body');scrollbinder=$(window);}else{page=$('#main');scrollbinder=page;}
menuOpenEvent=(sparkOptions.nestedMenu=="click-to-open"||isMobile)?'mousedown':'mouseenter';responsiveNavEnabled=(sparkOptions.mobileMenu=="select")?true:false;topMargin=$('#main').css('margin-top').replace(/px/,'');if($('body').hasClass('landing-page')){isLandingPage=true;navLinks=$('nav a[href^="#"]');checkNavIntegrity(navLinks);navLinks.each(function(){var target=$(this).attr('href').replace(/#/,'');$('#'+target).attr('id',target+'_modified');}).bind('mousedown',navLinks_handler).bind('click',function(event){event.preventDefault();});scroll_handler();scrollbinder.bind('scroll',scroll_handler);$('.logo a').mousedown(function(event){if(event.which==2||event.which==3){return;}
$('nav a:first').trigger('mousedown');}).click(function(event){event.preventDefault();});hash_handler();}
if(responsiveNavEnabled){$('nav.menu').sparkMobileMenu();}
$('nav > ul > li.spark-has-submenu').sparkSubmenus({'openEvent':menuOpenEvent});$('.spark-tooltip').sparkTooltips({'position':'top'});proceedMediaQueries();$internalLinks=(sparkOptions.smoothScrollAll)?$('a[href*=#]:not(a.no-animation, .no-animation a, .tabs a)'):$('a.animate');$internalLinks.click(function(){var target=$(this).attr('href');var splitedTarget=target.split('#');if(splitedTarget[0]!==''&&splitedTarget[0]!==window.location.href.split('#')[0]){return;}else{target='#'+splitedTarget[1];}
if($('nav a[href='+target+']').length>0){$('nav a[href='+target+']').trigger('mousedown');}else{if(target=='#'){targetPosition=0;}else{targetPosition=(isMobile)?$(target).offset().top:$(target).offset().top+page.scrollTop()-page.position().top;targetPosition=(isModernWebkitMobile)?targetPosition-topMargin:targetPosition;}
sparkScrollTo(targetPosition,target);}
return false;});$('a.targetblank').click(function(event){event.preventDefault();event.stopPropagation();window.open(this.href,'_blank');});var tabs=$('ul.tabs');tabs.each(function(i){var tab=$(this).find('> li > a');tab.mousedown(function(e){var contentLocation=$(this).attr('href');if(contentLocation.charAt(0)=="#"){e.preventDefault();tab.removeClass('active');$(this).addClass('active');$(contentLocation).show().addClass('active').siblings().hide().removeClass('active');}}).click(function(e){e.preventDefault();});});$("form.send-with-ajax").submit(function(e){e.preventDefault();var form=$(this),validationErrors=false;$('.form-error-msg').remove();form.find("input[type='email'], input[required]").each(function(index){var inputValue=$(this).val(),inputRequired=$(this).attr('required'),inputType=$(this).attr('type');$(this).removeClass('form-error');if(inputRequired&&inputValue==''){$(this).after('<div class="form-error-msg">Please fill out this field.</div>');$(this).addClass('form-error');validationErrors=true;}else if(inputType=='email'&&!$.sparkHelpers.isValidEmail(inputValue)){$(this).after('<div class="form-error-msg">Please enter an email address.</div>');$(this).addClass('form-error');validationErrors=true;}});if(!validationErrors){form.find('button:submit, input:submit').html('Sending...');form.find('.ajax-response').empty();$.post(form.attr('action'),form.serialize(),function(data){if(data.bFormSent){form.find('.ajax-response').empty().html(data.aResults[0]);form.find('button:submit, input:submit').html('Submit Form');form.find('#form-email, #form-name, #form-message').val('');}else{form.find('.ajax-response').empty().wrapInner('<div class="form-error-msg"></div>');form.find('.ajax-response div').html(data.aErrors[0]);form.find('button:submit, input:submit').html('Try Again');}},'json');}});sliders=$('.flexslider');initSliders(sliders);});$(window).hashchange(function(){if(isLandingPage){hash_handler();}})
$(window).load(function(){$('html').addClass('loaded');if(isLandingPage){hash_handler();}
setSlidersHeight(sliders);setTimeout(function(){$('img.responsive-img').sparkHdImages();},10);});$(window).resize(function(){proceedMediaQueries();setSlidersHeight(sliders);});navLinks_handler=function(event){if(event.which==2||event.which==3){return;}
$('nav a.active').removeClass('active');$(this).addClass('active');var target=$(this).attr('href');var targetPosition=(isMobile)?$(target+'_modified').offset().top:page.scrollTop()+$(target+'_modified').position().top;var targetPosition=(targetPosition==0||(isModernWebkitMobile&&targetPosition==topMargin))?targetPosition:targetPosition+20;var targetPosition=(!isFixedHeader&&(targetPosition<110))?0:targetPosition;var targetPosition=(isModernWebkitMobile)?targetPosition-topMargin:targetPosition;$.fn.sparkSubmenus('closeAll');sparkScrollTo(targetPosition,target);}
function sparkScrollTo(targetPosition,target){clearTimeout(hash_update_timer);if(isLandingPage){scrollbinder.unbind('scroll',scroll_handler);}
page.stop().animate({scrollTop:targetPosition},500,function(){if(target){clearTimeout(hash_update_timer);if(window.location.hash!==target){hash_update_timer=setTimeout(function(){location.hash=target;if(isLandingPage&&sparkOptions.trackSections&&typeof(_gaq)!="undefined"){_gaq.push(['_trackEvent','Landing-Page Sections','View',target]);}},10);}}
if(isLandingPage){scrollbinder.bind('scroll',scroll_handler);}
fix_iOSfive_bug();});}
function initSliders(sliders){var sliderOptions=new Array();sliders.each(function(index){if($(this).hasClass('animation-fade')){sliderOptions['animation']='fade';}else if($(this).hasClass('animation-slide')||isMobile){sliderOptions['animation']='slide';}else{sliderOptions['animation']='fade';}
if($(this).hasClass('animation-speed-fast')){sliderOptions['animationDuration']=300;}else if($(this).hasClass('animation-speed-slow')){sliderOptions['animationDuration']=900;}else{sliderOptions['animationDuration']=600;}
if($(this).hasClass('delay-between-slides-short')){sliderOptions['slideshowSpeed']=1500;}else if($(this).hasClass('delay-between-slides-long')){sliderOptions['slideshowSpeed']=6000;}else{sliderOptions['slideshowSpeed']=3000;}
if($(this).hasClass('hide-controls')){sliderOptions['controlNav']=false;}else{sliderOptions['controlNav']=true;}
if($(this).hasClass('auto-slide-off')){sliderOptions['slideshow']=false;}else{sliderOptions['slideshow']=true;}
if($(this).hasClass('loop-off')){sliderOptions['animationLoop']=false;}else{sliderOptions['animationLoop']=true;}
$(this).flexslider({animation:sliderOptions['animation'],slideshow:sliderOptions['slideshow'],slideshowSpeed:sliderOptions['slideshowSpeed'],animationDuration:sliderOptions['animationDuration'],directionNav:false,controlNav:sliderOptions['controlNav'],keyboardNav:true,mousewheel:false,slideToStart:0,animationLoop:sliderOptions['animationLoop'],pauseOnAction:true,pauseOnHover:true});});}
function proceedMediaQueries(){if($.sparkHelpers.isMobileView()){if(responsiveNavEnabled&&menuOpenEvent=='mousedown'){window.navLinks_hasSubmenu.bind('mousedown',navLinks_handler);}}else{if(responsiveNavEnabled&&menuOpenEvent=='mousedown'){window.navLinks_hasSubmenu.unbind('mousedown',navLinks_handler);}}}
function setSlidersHeight(sliders){sliders.each(function(){var sliderHeight=0;$(this).find('.slides > li').each(function(){slideHeight=$(this).height();if(sliderHeight<slideHeight){sliderHeight=slideHeight;}});$(this).find('ul.slides').css({'height':sliderHeight});});}
function checkNavIntegrity(navLinks){navLinks.each(function(){var linkHref=$(this).attr('href'),correspondingArticle=$(linkHref);if(correspondingArticle.length==0){var linkValue=$(this).html(),targetId=linkHref.replace(/#/,'');alert('Navigation Broken: The menu link "'+linkValue+'" points to a nonexistent ID "'+targetId+'". \n'
+'To fix this, change the link\'s target to a correct ID of one of the displayed sections (see "Theme Option" > "Landing-page Sections")');}});}
function hash_handler(){var hash=window.location.hash;if(hash){$('a[href='+hash+']').trigger('mousedown');}else{$('nav a.active').removeClass('active');$('nav a:first').addClass('active');sparkScrollTo(0);}}
function scroll_handler(){navLinks.each(function(){var target=$(this).attr('href'),targetPosition=(isMobile)?$(target+'_modified').offset().top:page.scrollTop()+$(target+'_modified').offset().top;targetPosition=(isModernWebkitMobile)?targetPosition-topMargin:targetPosition;targetLimit=320;if(scrollbinder.scrollTop()>(targetPosition-targetLimit)){$('nav a.active').removeClass('active');$(this).addClass('active');}
if($(this).is(':last-child')){if((isMobile&&($(window).scrollTop()>=$(document).height()-$(window).height()-50))||(!isMobile&&(page.scrollTop()+page.innerHeight()>=page[0].scrollHeight-50))){$('nav a.active').removeClass('active');$(this).addClass('active');}}});}
function fix_iOSfive_bug(){if(isMobile&&isFixedHeader){page.css('padding-right','1px');setTimeout(function(){page.css('padding-right','');},0);document.documentElement.style.paddingRight='1px';setTimeout(function(){document.documentElement.style.paddingRight='';},0);}}})(jQuery);